import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "./context/ThemeContext";
import VisitorInput from "./components/visitorPage/VisitorInput";
import MagnifierCursor from "@components/ui/MagnifierCursor"; // <-- shu yerda import qilamiz

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Farrukh's Portfolio",
  description: "Generated by me",
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f0f0f0" },
    { media: "(prefers-color-scheme: dark)", color: "#111111" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <VisitorInput />
          <div className="hidden md:block">
            <MagnifierCursor />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
